# Shopify app configuration - source of truth, deployed with `shopify app deploy`.
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1fefdba733ed40c0dd424574bd65ead"
name = "Disc Golf Inventory"
handle = "disc-golf-inventory"
application_url = "https://shopify.fusenv.com/embedded"
embedded = true

[access_scopes]
scopes = "read_files,write_files,write_inventory,read_inventory,read_locations,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify.fusenv.com/api/auth/shopify/token-exchange"
]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://shopify.fusenv.com/api/webhooks/shopify"
